CREATE TABLE Job.Jobs
(
	Id INT NOT NULL IDENTITY (-2147483648, 1),
	Title NVARCHAR(200) NOT NULL,
	StartTime DATETIME2(0) NOT NULL,
	EndTime DATETIME2(0) NOT NULL,
	CONSTRAINT [PK_Job_Jobs] PRIMARY KEY CLUSTERED (Id)
);
