CREATE TABLE [User].Users
(
	Id INT NOT NULL IDENTITY (-2147483648, 1),
	EmailAddress NVARCHAR(320) NOT NULL,
	[Password] NCHAR(64) NOT NULL,
	BusinessId INT NOT NULL,
	CONSTRAINT [PK_User_Users] PRIMARY KEY CLUSTERED (Id),
	INDEX [IX_User_Users_EmailAddress] NONCLUSTERED (EmailAddress)
);
