CREATE SCHEMA IF NOT EXISTS administrator;
CREATE SCHEMA IF NOT EXISTS business;
CREATE SCHEMA IF NOT EXISTS client;
CREATE SCHEMA IF NOT EXISTS deployment;
CREATE SCHEMA IF NOT EXISTS job;
CREATE SCHEMA IF NOT EXISTS technician;
CREATE SCHEMA IF NOT EXISTS "user";
