CREATE SCHEMA Administrator AUTHORIZATION dbo;
GO

CREATE SCHEMA Business AUTHORIZATION dbo;
GO

CREATE SCHEMA Client AUTHORIZATION dbo;
GO

CREATE SCHEMA Deployment AUTHORIZATION dbo;
GO

CREATE SCHEMA Job AUTHORIZATION dbo;
GO

CREATE SCHEMA Technician AUTHORIZATION dbo;
GO

CREATE SCHEMA [User] AUTHORIZATION dbo;
GO
